services:
  web:
    runtime: node
    build: npm run build
    run: npm run start
    port: 3000
    env:
      BACKEND_API_URL: http://api:3001
    depends_on:
      - api

  api:
    runtime: node
    workdir: server
    build: npm run build
    run: node dist/server.mjs
    port: 3001
    internal: true
